### ISSUE TITLE
Data modelling for Users, Mentorships, Questionnaires

### ISSUE THREAD

**Issue by andycroll** [goodscary/firstrubyfriend#10]
Proposed Architecture

Break it into PRs for each of the tables and we can see if the naming is correct.

## User

unsubscribed_at
unsubscribed_reason [ghosted_mentor/ghosted_applicant/requested_removal]
availilble_as_mentor_at
requested_mentorship_at
city
country_code
lat
lng
demographic_year_of_birth
demographic_year_started_ruby
demographic_year_started_programming
demographic_underrepresented_group
-> Languages

## Mentorship

mentor  -> User
applicant -> User
standing [active/ended]
applicant_month_x_email_sent_at (1 thru 6)
mentor_month_x_email_sent_at (1 thru 6)

## MentorQuestionnaire

_All the questions in the existing survey…_
respondent -> User
preferred_style_career [T/F]
preferred_style_code [T/F]

## MenteeQuestionnaire

_All the questions in the existing survey…_
respondent -> User
looking_for_career [T/F]
looking_for_code [T/F]
looking_for_underrepresented_group [T/F]

**Comment by pratiktamang** [comment]
- [ ] User Model [PR](https://github.com/goodscary/firstrubyfriend/pull/11)
- [ ] Mentorship Model [PR](https://github.com/goodscary/firstrubyfriend/pull/12)
- [ ] Mentor Questionnaire Model (WIP)
- [ ] Mentee Questionnaire Model (TODO)

**Comment by pratiktamang** [comment]
The proposed schema here has been implemented. Closing it out 🎉
